"""empty message

Revision ID: 57b615eda834
Revises: 93d1d1aebe00
Create Date: 2025-05-23 20:11:55.290145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b615eda834'
down_revision = '93d1d1aebe00'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('recommends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_recommends_post_id',  # <-- ИМЯ ОБЯЗАТЕЛЬНО
            'posts',
            ['post_id'],
            ['id']
        )
        batch_op.drop_column('Authors')
        batch_op.drop_column('Name')
        batch_op.drop_column('Category')
        batch_op.drop_column('Link')
        batch_op.drop_column('Picture')
        batch_op.drop_column('Summary')
        batch_op.drop_column('Learners')
        batch_op.drop_column('Rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Rating', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('Learners', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('Summary', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Picture', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Link', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('Authors', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
